# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Ant@1
  displayName: 'executing build.xml'
  inputs:
    buildFile: 'build.xml'
    options: 
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'

- task: PublishBuildArtifacts@1
  displayName: "Publishing artifacts"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    

- task: DockerInstaller@0
  displayName: "docker installer"
  inputs:
    dockerVersion: '17.09.0-ce'
    
- task: Docker@2
  displayName: "Image pulling to ACR"
  inputs:
    containerRegistry: 'Ant ACR connection'
    repository: 'swedacr'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'